package com.xmlalabash.extensions;

import com.delightfulcomputing.xproc.TextDiff;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class TextDiffTest {
    @Test public void testmain() {
        // TextDiff classUnderTest = new TextDiff(null, null);
        assertTrue(true);
    }
}
